name: Lumi Remote Access
version: 1.3.4
slug: lumi_remote_access
description: >-
  Lumi Remote Access
url: 'https://github.com/sameeraakbar/lumi-addons'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
map:
  - 'config:rw'

options:
  hostname: ''
  ssh_port: 22
  username: lumicloud
  remote_ip_address: "127.0.0.1"
  remote_port: 6000
  remote_forwarding: []
  other_ssh_options: '-N'
  force_keygen: false
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_ip_address: str
  remote_port: int
  local_ip_address: str?
  local_port: int?
  remote_forwarding:
    - str
  other_ssh_options: str
  force_keygen: bool
